[package]
name = "cohere-commit"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.98"
reqwest = { version = "0.12.15", features = ["json", "rustls-tls"] }
serde_json = "1.0.140"
tokio = { version = "1.45.0", features = ["full"] }
